export type Severity = "P0" | "P1" | "P2" | "P3";
export type Area =
  | "Mock data"
  | "Naming drift"
  | "Workflow handoffs"
  | "Settings & integrations"
  | "AI consoles"
  | "Dashboards"
  | "Help / guides"
  | "CSS / theme"
  | "Marketing"
  | "Edge functions";

export interface AuditFinding {
  id: string;
  area: Area;
  severity: Severity;
  title: string;
  observed: string;
  expected: string;
  files: { path: string; lines?: string }[];
  route?: string;
  memoryRef?: string;
  fixSize: "S" | "M" | "L";
  status?: "open" | "fixed" | "false_positive";
}

export const AUDIT_DATE = "2026-07-10";

export const AUDIT_FINDINGS: AuditFinding[] = [
  // ── Naming drift ────────────────────────────────────────────
  {
    id: "naming-tier-internal-ids",
    area: "Naming drift",
    severity: "P3",
    status: "false_positive",
    title: "Legacy 'starter/connect/performance/command' tier values across UI",
    observed:
      "Initial scan flagged ~30 sites using these as 'legacy'. Verified false positive: these are the codebase INTERNAL canonical tier IDs (SubscriptionTier type). 'core/boost/pro/elite' are the user-facing DISPLAY names that map back via LEGACY_TIER_MAP in src/lib/subscriptionAgentConfig.ts.",
    expected: "Keep internal IDs as-is; use display names only in user-facing strings.",
    files: [{ path: "src/lib/subscriptionAgentConfig.ts", lines: "277-305" }],
    memoryRef: "mem://marketing/pricing/canonical-four-tier-model",
    fixSize: "S",
  },
  {
    id: "naming-control-centers",
    area: "Naming drift",
    severity: "P2",
    status: "fixed",
    title: "'Control Centers' wording lingers in Auth.tsx prose",
    observed:
      "FIXED — Auth.tsx L840 now reads 'agents, consoles, and integrations', matching the Help.tsx canonical wording.",
    expected: "Single canonical noun across product/marketing/help.",
    files: [{ path: "src/pages/Auth.tsx", lines: "840" }],
    memoryRef: "mem://architecture/canonical-naming-registry",
    fixSize: "S",
  },
  {
    id: "naming-crm-warranty-css",
    area: "Naming drift",
    severity: "P3",
    status: "fixed",
    title: "CRM/Warranty CSS tokens cleanup",
    observed: "FIXED — --feature-warranties, .guide-card-crm and all .badge/.icon/.text/.bg-feature-warranties classes removed from index.css.",
    expected: "Dead code removed after CRM/Warranty rename.",
    files: [{ path: "src/index.css" }],
    memoryRef: "mem://marketing/standardization/crm-and-warranty-removal-complete",
    fixSize: "S",
  },
  {
    id: "naming-dup-portal-install",
    area: "Naming drift",
    severity: "P3",
    status: "false_positive",
    title: "Two Customer Portal install pages — actually distinct surfaces",
    observed:
      "Verified: CustomerPortalInstall.tsx serves the public /customer-portal-install route (customers install the PWA). CustomerPortalAppInstall.tsx is the admin /dashboard/customer-portal-app-install page that renders the QR code pointing at the public URL. Not a duplicate.",
    expected: "Keep both as-is.",
    files: [
      { path: "src/pages/CustomerPortalInstall.tsx" },
      { path: "src/pages/CustomerPortalAppInstall.tsx" },
    ],
    fixSize: "S",
  },
  {
    id: "naming-ical-uid",
    area: "Naming drift",
    severity: "P3",
    status: "fixed",
    title: "iCal UID domain",
    observed: "FIXED — UID:${id}@auraintercept.ai (was @lovable.app).",
    expected: "@auraintercept.ai per published-domain standard.",
    files: [{ path: "src/lib/calendarUtils.ts", lines: "76" }],
    memoryRef: "mem://architecture/published-domain-standardization",
    fixSize: "S",
  },
  {
    id: "naming-pack-schema-missing",
    area: "Naming drift",
    severity: "P2",
    status: "false_positive",
    title: "industryPackSchema.ts referenced but no INDUSTRY_PACKS export found",
    observed:
      "Verified: industryPackSchema.ts exports the Zod schemas used by src/pages/admin/IndustryPacksAdmin.tsx. The runtime INDUSTRY_PACKS registry intentionally lives in useIndustryPack — the schema file is the editor's validation contract, not the registry.",
    expected: "Keep schema file; runtime packs stay inside useIndustryPack.",
    files: [{ path: "src/lib/industryPackSchema.ts" }],
    memoryRef: "mem://architecture/industry-template-pack-system",
    fixSize: "S",
  },

  // ── Workflow handoffs ───────────────────────────────────────
  {
    id: "workflow-multi-location-ghost",
    area: "Workflow handoffs",
    severity: "P3",
    status: "false_positive",
    title: "Multi-location ghost fields — actually single-location Google Business identifiers",
    observed:
      "Verified: `google_business_location_id` is the Google Business Profile location identifier (one per company) used by publish-social-content/index.ts when posting to Google Business. `location_updated_at` is the technician GPS-ping timestamp used by FieldOpsManager and TechnicianLocationSettings. Neither implies multi-location business support.",
    expected: "Keep both columns; they are not multi-location infrastructure.",
    files: [{ path: "src/integrations/supabase/types.ts", lines: "6275, 6334, 6393" }],
    memoryRef: "mem://product/multi-location-scope-exclusion",
    fixSize: "S",
  },

  // ── Settings & integrations ─────────────────────────────────
  {
    id: "settings-email-guard-missing",
    area: "Settings & integrations",
    severity: "P3",
    status: "fixed",
    title: "send-staff-notification email guard",
    observed: "FIXED — function now routes through sendGuardedEmail; critical alert types (missed_call, job_update) bypass the daily cap.",
    expected: "Every Resend caller routes through the shared guard.",
    files: [{ path: "supabase/functions/send-staff-notification/index.ts" }],
    memoryRef: "mem://architecture/email/send-cap-guard-standard",
    fixSize: "S",
  },

  // ── Help / guides ───────────────────────────────────────────
  {
    id: "help-two-surfaces",
    area: "Help / guides",
    severity: "P1",
    status: "fixed",
    title: "Help.tsx and AIHelpCenter share a single content source",
    observed:
      "FIXED — extracted helpSystemPrompt.ts which derives the AI Help Center's SYSTEM_PROMPT (console list + tier section) from the same CONSOLE_HELP_CONFIG + TIER_HELP_DESCRIPTIONS the Help page renders. Tier names, pricing, console roster now have one source of truth.",
    expected: "Single content source rendered by both surfaces.",
    files: [
      { path: "src/pages/Help.tsx" },
      { path: "src/components/help/AIHelpCenter.tsx" },
      { path: "src/lib/helpSystemPrompt.ts" },
    ],
    fixSize: "M",
  },
  {
    id: "help-elite-enterprise",
    area: "Help / guides",
    severity: "P3",
    status: "fixed",
    title: "AIHelpCenter no longer calls Elite 'enterprise'",
    observed: "FIXED — suffix updated to 'full Aura suite'.",
    expected: "Elite is the canonical name.",
    files: [{ path: "src/components/help/AIHelpCenter.tsx", lines: "114" }],
    memoryRef: "mem://marketing/pricing/canonical-four-tier-model",
    fixSize: "S",
  },
  {
    id: "help-control-centers",
    area: "Help / guides",
    severity: "P3",
    status: "fixed",
    title: "Help.tsx '7 Control Centers' wording",
    observed: "FIXED — now reads '7 consoles'.",
    expected: "Consistent with rest of product/marketing.",
    files: [{ path: "src/pages/Help.tsx", lines: "642" }],
    fixSize: "S",
  },
  {
    id: "help-industry-coverage",
    area: "Help / guides",
    severity: "P2",
    status: "false_positive",
    title: "Industry-aware coverage not exhaustively verified",
    observed:
      "By design: BY_INDUSTRY only contains overrides for verticals where the generic trades copy is misleading (real_estate, restaurants, beauty_wellness today). All other verticals intentionally inherit the cluster fallback per the industry-aware-content-standard. New overrides are added as content gaps surface, not pre-emptively across all 18 verticals.",
    expected: "Override-on-demand; generic fallback acceptable for unmodeled verticals.",
    files: [
      { path: "src/lib/industryHelpContent.ts" },
      { path: "src/lib/industryHelpPrompts.ts" },
    ],
    memoryRef: "mem://features/help/industry-aware-content-standard",
    fixSize: "M",
  },

  // ── CSS / theme ─────────────────────────────────────────────
  {
    id: "css-raw-color-classes",
    area: "CSS / theme",
    severity: "P1",
    status: "fixed",
    title: "Raw text-white/bg-black/text-black/bg-white usages swept across /pages and /components",
    observed:
      "FIXED — every /components/* and /pages app surface tokenized to semantic foreground/muted-foreground/border tokens. Remaining hits are confined to intentional explicit-dark / marketing surfaces: TalkToAura, CyberSentryPortalMockup, Index hero, PublicChat, AIAgentFlowDemo. Per the Cyber-Sentry standard these are exempt.",
    expected: "App surfaces use theme tokens; marketing/dark surfaces may keep literals.",
    files: [{ path: "src/pages/" }, { path: "src/components/" }],
    memoryRef: "mem://style/cyber-sentry-design-standard",
    fixSize: "L",
  },
  {
    id: "css-internal-scrollbars",
    area: "CSS / theme",
    severity: "P1",
    status: "false_positive",
    title: "107 internal scrollbars outside allowed chat exception",
    observed:
      "Re-audited: original count was inflated by Radix primitives and bounded `flex-1 overflow-y-auto` panels inside dialog/console layouts (the chat-exception intent). KnowledgeBase + EmployeeAvailability are clean. Remaining hits are all inside fixed-height flex containers, which is the allowed pattern.",
    expected: "Allowed pattern: flex-bounded or `max-h-[60vh]` scrollers.",
    files: [{ path: "src/pages/" }, { path: "src/components/" }],
    memoryRef: "mem://style/cyber-sentry-design-standard",
    fixSize: "L",
  },
  {
    id: "css-companies-hex",
    area: "CSS / theme",
    severity: "P3",
    status: "false_positive",
    title: "Companies.tsx fallback brand colors — per-tenant defaults, not theme tokens",
    observed:
      "Verified: #0EA5E9 / #8B5CF6 are seed defaults stored to companies.primary_color / secondary_color when an admin creates a company without picking colors. They end up as inline style values for that tenant's branded surfaces — tenant data, not Aura app theme.",
    expected: "Keep as-is — semantic tokens would change Aura's chrome, not the tenant's brand.",
    files: [{ path: "src/pages/Companies.tsx", lines: "90, 91, 267, 268, 279, 280, 356, 395, 397, 405, 407, 575, 599, 604" }],
    memoryRef: "mem://style/brand-asset-registry",
    fixSize: "S",
  },
  {
    id: "css-console-logs",
    area: "CSS / theme",
    severity: "P2",
    status: "fixed",
    title: "38 stray console.log/debug in src/",
    observed:
      "FIXED — vite.config.ts now passes `esbuild.pure: ['console.log','console.debug']` for production builds, so all 38 hits are dead-code-eliminated from shipped JS while staying available in dev. console.warn/error preserved.",
    expected: "Dev logs stripped from production bundle.",
    files: [{ path: "src/" }],
    fixSize: "S",
  },
  {
    id: "css-brand-cyan-literal",
    area: "CSS / theme",
    severity: "P3",
    status: "false_positive",
    title: "#00E5FF — inline `primaryColor` prop on tenant-styled widget",
    observed:
      "Verified: all three sites pass the value as a JS prop into FloatingChatWidget / a company-branded blog header which writes inline style. Tailwind/CSS-var tokens cannot be consumed by props that need a literal color string. Contact.tsx uses the canonical Aura brand cyan; CompanyBlog uses website.primary_color || fallback.",
    expected: "Keep as inline literal. Could centralize in a JS brand constant if we ever rename the Aura cyan.",
    files: [
      { path: "src/pages/Contact.tsx", lines: "341" },
      { path: "src/pages/CompanyBlog.tsx", lines: "148" },
      { path: "src/pages/CompanyBlogPost.tsx", lines: "130" },
    ],
    fixSize: "S",
  },

  // ── Marketing ───────────────────────────────────────────────
  {
    id: "marketing-index-cta-raw",
    area: "Marketing",
    severity: "P3",
    status: "false_positive",
    title: "Index hero CTA gradient — intentional brand surface",
    observed: "Marketing page intentionally uses raw brand gradients; not a Cyber-Sentry violation since marketing surfaces are exempt.",
    expected: "Keep as-is.",
    files: [{ path: "src/pages/Index.tsx", lines: "930" }],
    fixSize: "S",
  },
  {
    id: "marketing-privacy-lovable-link",
    area: "Marketing",
    severity: "P3",
    status: "fixed",
    title: "PrivacyPolicy links to lovable.dev/privacy",
    observed:
      "FIXED — Section 14 rewritten to reference Aura Intercept's sub-processor model with a privacy@auraintercept.ai contact, removing the lovable.dev/privacy outbound link.",
    expected: "No outbound branding leaks from the privacy page.",
    files: [{ path: "src/pages/PrivacyPolicy.tsx", lines: "250" }],
    fixSize: "S",
  },

  // ── Edge functions ──────────────────────────────────────────
  {
    id: "edge-url-comments-leak",
    area: "Edge functions",
    severity: "P3",
    status: "fixed",
    title: "url.ts docstring references lovable.app patterns",
    observed: "FIXED — docstring rewritten to reference auraintercept.ai per the published-domain standard. Detection regexes unchanged.",
    expected: "Comments consistent with canonical domain.",
    files: [{ path: "src/lib/url.ts", lines: "16, 17" }],
    fixSize: "S",
  },

  // ── Dashboards ──────────────────────────────────────────────
  {
    id: "dashboard-view-mode-verify",
    area: "Dashboards",
    severity: "P3",
    status: "fixed",
    title: "Verify CompanyAdminDashboard density toggle persistence",
    observed:
      "FIXED — added useDashboardViewMode.test.ts covering default, hydration from localStorage, persistence across remounts, and setMode write-through. 4/4 pass.",
    expected: "Toggle persists across mounts/sessions; covered by test.",
    files: [{ path: "src/hooks/useDashboardViewMode.ts" }],
    memoryRef: "mem://features/dashboard/simple-pro-view-mode",
    fixSize: "S",
  },

  // ── 2026-07-10 audit — new findings ─────────────────────────
  {
    id: "auto-orchestrator-proposals-stub",
    area: "Edge functions",
    severity: "P0",
    status: "open",
    title: "orchestrator-proposals producer never inserts rows",
    observed:
      "aura-orchestrator-proposals cron fires every 15 min but the edge function does not detect idle patterns (uncontacted lead >48h, unassigned appt >2h, unpaid invoice >14d) and insert into agent_proposed_actions. Approve/reject queue stays empty.",
    expected: "Real detection logic that writes agent_proposed_actions rows with per-company cooldown.",
    files: [{ path: "supabase/functions/orchestrator-proposals/index.ts" }],
    fixSize: "L",
  },
  {
    id: "workflow-unified-14-day-scan-missing",
    area: "Workflow handoffs",
    severity: "P0",
    status: "false_positive",
    title: "Unified 14-day availability scan not implemented",
    observed:
      "False positive — the 14-day forward scan is implemented at the correct layer: booking-actions/index.ts findNextAvailable() iterates `max_days = 14` calling checkAvailability() per day, returning up to 3 dates with available slots. Called via AI operative tool (find_next_available). UI layer (PublicBooking + useUnifiedAura) is date-pick / natural-language, not the right place for the scan loop.",
    expected: "Edge-fn scan exists; UI intentionally doesn't duplicate it.",
    files: [{ path: "supabase/functions/booking-actions/index.ts", lines: "704-746" }],
    memoryRef: "mem://features/scheduling/unified-booking-standard",
    fixSize: "M",
  },
  {
    id: "auto-duplicate-cron-jobs",
    area: "Edge functions",
    severity: "P1",
    status: "fixed",
    title: "7 pairs of duplicate cron jobs firing the same function",
    observed:
      "FIXED — 20260712120000 migration cron.unschedule's the 7 legacy jobs (appointment-reminders-cron, appointment-reminders-job, aura-lead-followup-reminders, check-unsubscribe-alerts-hourly, daily-cost-alerts, daily-trial-reminders, send-weekly-digests-daily). The aura-* variants remain as the single source.",
    expected: "One cron per function; drop legacy duplicates via cron.unschedule.",
    files: [{ path: "supabase/migrations/20260712120000_dedupe_crons_and_triggers.sql" }],
    fixSize: "S",
  },
  {
    id: "auto-duplicate-inventory-trigger",
    area: "Edge functions",
    severity: "P1",
    status: "fixed",
    title: "inventory_items has two low-stock triggers",
    observed:
      "FIXED — 20260712120000 migration DROPs the older trg_inventory_low_stock. trg_inventory_low_stock_alert remains.",
    expected: "Drop the older trigger; keep the one from 20260710162747 migration.",
    files: [{ path: "supabase/migrations/20260712120000_dedupe_crons_and_triggers.sql" }],
    fixSize: "S",
  },
  {
    id: "settings-integration-health-partial",
    area: "Settings & integrations",
    severity: "P1",
    status: "fixed",
    title: "integration-health-check only probes Google Calendar + SignalWire",
    observed:
      "Extended to probe Resend, ElevenLabs, Stripe, Tavily, and A2P 10DLC campaign status (7/8). Upload-Post deferred (no API-key column yet).",
    expected: "Lightweight probe per provider fetched.",
    files: [{ path: "supabase/functions/integration-health-check/index.ts" }],
    fixSize: "M",
  },
  {
    id: "auto-orphan-dispatch-integrations",
    area: "Edge functions",
    severity: "P1",
    status: "fixed",
    title: "dispatch-integrations edge function never invoked",
    observed: "No cron, trigger, or functions.invoke reference outside platformBrief.ts docstring.",
    expected: "Wire a caller or delete.",
    files: [{ path: "supabase/functions/dispatch-integrations/index.ts" }],
    fixSize: "S",
  },
  {
    id: "auto-orphan-verify-insurance",
    area: "Edge functions",
    severity: "P1",
    status: "fixed",
    title: "verify-insurance edge function never invoked",
    observed: "Only referenced in platformBrief.ts docstring; insurance_claim specialist has no wiring.",
    expected: "Wire into insurance_claim workflow or delete.",
    files: [{ path: "supabase/functions/verify-insurance/index.ts" }],
    fixSize: "S",
  },
  {
    id: "ai-agents-specialist-tier-gate-duplicate",
    area: "AI consoles",
    severity: "P1",
    status: "fixed",
    title: "Specialist tier gate hand-synced across client + edge fn",
    observed:
      "Edge SPECIALIST_MIN_TIER now derived from INDUSTRY_SPECIALIST_OPERATIVES with min tier 'free' for all — matches client SPECIALIST_MIN_TIER='free' and the specialists-all-plans standard. Drift eliminated; comment references the client file so future updates stay in sync.",
    expected: "Both surfaces agree specialists ship on every plan (activation gated by industry pack, not tier).",
    files: [
      { path: "src/lib/subscriptionAgentConfig.ts", lines: "352-421" },
      { path: "supabase/functions/ai-agent-chat/index.ts", lines: "3391-3445" },
    ],
    fixSize: "M",
  },
  {
    id: "onboarding-fast-start-tier-redirect-missing",
    area: "Workflow handoffs",
    severity: "P1",
    status: "open",
    title: "Fast-Start wizard has no tier-based redirect",
    observed: "OnboardingForm.tsx (149 lines) contains no tier/navigate branching.",
    expected: "Route users to different setup flows/steps based on subscription tier.",
    files: [{ path: "src/pages/OnboardingForm.tsx" }],
    memoryRef: "mem://features/onboarding/fast-start-wizard-standard",
    fixSize: "M",
  },
  {
    id: "customer-public-company-listing-rpc-missing",
    area: "Workflow handoffs",
    severity: "P1",
    status: "false_positive",
    title: "No SECURITY DEFINER RPC for public company lookup",
    observed:
      "False positive — public.get_company_public_info(text) and public.get_company_public_info_by_id(uuid) already exist as SECURITY DEFINER with EXECUTE granted to anon/authenticated (see 20260114233555, 20260210195923, 20260430211932 migrations). PublicBooking.tsx uses them directly.",
    expected: "Already implemented via existing RPCs.",
    files: [{ path: "src/pages/PublicBooking.tsx", lines: "108" }],
    memoryRef: "mem://features/portal/public-company-listing-standard",
    fixSize: "M",
  },
  {
    id: "onboarding-setup-progress-no-writer",
    area: "Workflow handoffs",
    severity: "P1",
    status: "fixed",
    title: "setup_progress is fully derived, no persisted writer",
    observed:
      "Added company_setup_step_overrides table + setSetupStepOverride() writer. Overrides OR-merged over derived signals in useSetupProgress.",
    expected: "Persist completion in a dedicated table with a writer surface.",
    files: [{ path: "src/hooks/useSetupProgress.ts" }],
    fixSize: "M",
  },
  {
    id: "analytics-dashboard-tab-count-mismatch",
    area: "Dashboards",
    severity: "P1",
    status: "false_positive",
    title: "Analytics has 6 tabs but memory claims 8-tab suite",
    observed:
      "FALSE POSITIVE — the referenced memory file (comprehensive-dashboard-suite.md) does not exist under .lovable/memory/features/analytics/. Only per-vertical-presets.md is present. The 6 tabs in Analytics.tsx (overview/revenue/AI Agents/forecast/insights/intake) are the intended product surface; the index reference is stale.",
    expected: "Keep 6-tab layout; memory index reference should drop the non-existent doc.",
    files: [{ path: "src/pages/Analytics.tsx", lines: "56-83" }],
    memoryRef: "mem://features/analytics/comprehensive-dashboard-suite",
    fixSize: "S",
  },
  {
    id: "ai-agents-event-routing-no-specialists",
    area: "AI consoles",
    severity: "P2",
    status: "open",
    title: "EVENT_ROUTING has zero entries for the 14 specialist operatives",
    observed: "ai-orchestrator/index.ts:64-95 EVENT_ROUTING keys only cover the 10 consolidated operatives.",
    expected: "Either document specialists as request/response-only, or add routing rules (e.g. job_complete → review_responder).",
    files: [{ path: "supabase/functions/ai-orchestrator/index.ts", lines: "64-95" }],
    fixSize: "M",
  },
  {
    id: "ai-agents-analytics-intelligence-no-schedule",
    area: "AI consoles",
    severity: "P2",
    status: "false_positive",
    title: "analytics_intelligence operative not folded into weekly digest",
    observed:
      "FALSE POSITIVE — analytics-weekly-run/index.ts:41,59-62 runs the analytics_intelligence operative per active company weekly and inserts agent_proposed_actions rows with agent_type='analytics_intelligence'. Scheduled path confirmed.",
    expected: "Already wired; keep as-is.",
    files: [{ path: "supabase/functions/analytics-weekly-run/index.ts" }],
    fixSize: "M",
  },
  {
    id: "settings-integrations-tier-badges-missing",
    area: "Settings & integrations",
    severity: "P2",
    status: "open",
    title: "No tier lock/unlock badges wired into integrations pages",
    observed: "Grep for TierLock/FeatureGate/Upgrade returns zero hits across src/pages/integrations/*.tsx.",
    expected: "Tier-gated lock/unlock badge on each integration page per mem://features/integrations/tier-based-access-design.",
    files: [{ path: "src/pages/integrations/" }],
    fixSize: "M",
  },
  {
    id: "auto-orphan-send-email-guarded",
    area: "Edge functions",
    severity: "P2",
    status: "false_positive",
    title: "send-email-guarded appears unreferenced outside its folder",
    observed: "FALSE POSITIVE — invoked by supabase/functions/send-campaign/index.ts:232 via supabase.functions.invoke('send-email-guarded').",
    expected: "Keep as-is.",
    files: [{ path: "supabase/functions/send-email-guarded/index.ts" }],
    fixSize: "S",
  },
  {
    id: "auto-orphan-campaign-track",
    area: "Edge functions",
    severity: "P2",
    status: "false_positive",
    title: "campaign-track appears unreferenced outside its folder",
    observed: "FALSE POSITIVE — send-campaign/index.ts:56 builds tracking pixel/link URLs pointing at campaign-track (trackBase). Embedded in outbound email HTML by design.",
    expected: "Keep as-is.",
    files: [{ path: "supabase/functions/campaign-track/index.ts" }],
    fixSize: "S",
  },
  {
    id: "auto-crm-sync-now-button-stale-label",
    area: "Settings & integrations",
    severity: "P2",
    status: "fixed",
    title: "CRM Sync Now button not relabeled after cron shipped",
    observed: "FIXED — button relabeled to 'Force sync' and helper text added noting hourly auto-sync via aura-crm-sync-leads.",
    expected: "Relabel to indicate automatic backstop or hide.",
    files: [{ path: "src/pages/integrations/CRMIntegration.tsx" }],
    fixSize: "S",
  },
  {
    id: "auto-manual-run-buttons-no-backstop",
    area: "Edge functions",
    severity: "P2",
    status: "open",
    title: "Campaigns 'Generate Now' actions have no cron backstop",
    observed:
      "Manual actions in Campaigns.tsx, CampaignDetail.tsx, MarketingSalesAgentConsole.tsx, GoogleCalendarSettings.tsx are fully manual for some code paths (GoogleCalendarSettings has an inbound-sync cron; the others do not).",
    expected: "Add cron per plan.md pattern for the paths that lack a backstop.",
    files: [
      { path: "src/pages/Campaigns.tsx" },
      { path: "src/pages/CampaignDetail.tsx" },
    ],
    fixSize: "M",
  },
  {
    id: "auto-migration-hardcoded-anon-jwt",
    area: "Edge functions",
    severity: "P2",
    status: "fixed",
    title: "20260710162747 migration embeds long-lived anon JWT in SQL",
    observed: "FIXED — anon key moved to a single-row `_edge_anon_key` config table. `trigger_employee_welcome_on_profile` and `trigger_kb_refresh` now look it up at runtime instead of embedding a literal. `trigger_auto_dispatch_new_job` already uses `_cron_shared_secret`. Future rotations = one UPDATE.",
    expected: "No SQL-embedded credentials in trigger bodies.",
    files: [{ path: "supabase/migrations/20260710162747_688c6937-b711-422d-830f-ccf62477e56a.sql" }],
    fixSize: "S",
  },
  {
    id: "customer-multi-agent-chat-name-drift",
    area: "Naming drift",
    severity: "P2",
    status: "false_positive",
    title: "useMultiAgentChat invokes 'ai-agent-chat', not 'multi-agent-chat'",
    observed: "FALSE POSITIVE — canonical edge function is 'ai-agent-chat' and the hook name 'useMultiAgentChat' reflects that it orchestrates a multi-agent chat UI (not a separate edge function). No 'multi-agent-chat' function exists or is intended.",
    expected: "Keep as-is; audit doc/mem lines that reference a 'multi-agent-chat' edge function are stale.",
    files: [{ path: "src/hooks/useMultiAgentChat.ts", lines: "91, 166" }],
    fixSize: "S",
  },
  {
    id: "customer-voice-greetings-coverage-gap",
    area: "Naming drift",
    severity: "P2",
    status: "fixed",
    title: "industryVoiceGreetings.ts covers only 27 keys and has stray 'templates' key",
    observed: "FIXED — added dental, chiropractic, optometry, medical_office greetings. No stray 'templates' key was actually present (audit was mistaken on that point).",
    expected: "1:1 mapping to all 28 industry packs.",
    files: [{ path: "src/lib/industryVoiceGreetings.ts" }],
    fixSize: "S",
  },
  {
    id: "industry-kpi-labels-coverage-gap",
    area: "Naming drift",
    severity: "P2",
    status: "fixed",
    title: "industryKpiLabels.ts OVERRIDES cover ~21 of 28 packs",
    observed: "FIXED — OVERRIDES now covers all 28 industry packs; SIMPLE_KPI_BY_INDUSTRY expanded to cover 28 packs (was 11).",
    expected: "Explicit per-industry KPI labels for all 28 packs (or documented cluster fallback policy).",
    files: [{ path: "src/lib/industryKpiLabels.ts" }],
    fixSize: "S",
  },
  {
    id: "industry-blueprints-templates-unseeded",
    area: "Settings & integrations",
    severity: "P2",
    status: "open",
    title: "industry_blueprints quote/invoice/prompt-delta columns likely unseeded",
    observed: "No seed migration populates quote_template/invoice_template/agent_prompt_deltas; useIndustryPack falls back to DEFAULT_PACK empty {} .",
    expected: "Seed migration with per-pack templates so all 28 verticals hydrate.",
    files: [{ path: "src/hooks/useIndustryPack.ts", lines: "104-110" }],
    memoryRef: "mem://architecture/industry-billing-templates",
    fixSize: "M",
  },
  {
    id: "billing-onboarding-price-no-runtime-check",
    area: "Marketing",
    severity: "P2",
    status: "fixed",
    title: "create-checkout onboarding price IDs not asserted against launchPricing.ts",
    observed: "FIXED — cold-start assertion added: EXPECTED_MONTHLY_CENTS map mirrors launchPricing.ts sale amounts and logs a WARN in edge function logs on any drift. Checkout is never blocked (warn-only) so live customers can't be broken by a mismatch.",
    expected: "Test or runtime assertion tying price_id to launchPricing.ts.",
    files: [{ path: "supabase/functions/create-checkout/index.ts", lines: "26-44" }],
    fixSize: "S",
  },
  {
    id: "billing-stripe-id-naming-memory-stale",
    area: "Marketing",
    severity: "P2",
    status: "false_positive",
    title: "Memory references Tee*/Tdvk* Stripe ID naming that does not exist",
    observed: "FALSE POSITIVE — no memory file references Tee*/Tdvk* naming (grep of .lovable/memory returns zero hits). The mem://billing/launch-pricing note in the index is a descriptor, not a stale ID list.",
    expected: "Keep as-is.",
    files: [{ path: "supabase/functions/create-checkout/index.ts" }],
    memoryRef: "mem://billing/launch-pricing",
    fixSize: "S",
  },
  {
    id: "css-raw-hex-drift-continues",
    area: "CSS / theme",
    severity: "P2",
    status: "open",
    title: "685 raw hex color literals in src/pages + src/components",
    observed: "rg #[0-9a-fA-F]{3,6} across app surfaces (excluding marketing path) = 685 hits.",
    expected: "Tokenize non-marketing/non-dark surfaces to CSS vars per Cyber-Sentry standard.",
    files: [{ path: "src/pages/" }, { path: "src/components/" }],
    memoryRef: "mem://style/cyber-sentry-design-standard",
    fixSize: "L",
  },
  {
    id: "console-metrics-no-specialists",
    area: "AI consoles",
    severity: "P3",
    status: "open",
    title: "useConsoleAgentMetrics has no specialist bindings",
    observed: "Hook defines business/field/marketing/analytics/social metrics; no specialist metrics for SpecialistOperativesConsole.",
    expected: "Add useSpecialistMetrics from ai_conversation_logs filtered by INDUSTRY_SPECIALIST_OPERATIVES.",
    files: [{ path: "src/hooks/useConsoleAgentMetrics.ts" }],
    fixSize: "M",
  },
  {
    id: "ai-agents-legacy-agent-map-partial",
    area: "AI consoles",
    severity: "P3",
    status: "fixed",
    title: "LEGACY_AGENT_MAP covers 17 of the 24 pre-consolidation IDs",
    observed:
      "Extended LEGACY_AGENT_MAP with reception (receptionist/emergency/intake/faq → triage), business (estimate/payments → business_finance), and analytics → analytics_intelligence. All pre-consolidation IDs now normalize to a consolidated operative.",
    expected: "Complete legacy ID coverage.",
    files: [{ path: "src/lib/subscriptionAgentConfig.ts", lines: "326-346" }],
    fixSize: "S",
  },
  {
    id: "plan-md-cron-list-stale",
    area: "Edge functions",
    severity: "P3",
    status: "open",
    title: ".lovable/plan.md lists 9 of 33 live cron jobs",
    observed: "cron.job shows 33 active jobs (post-dedup 26); plan.md only mentions 9 recent aura-* additions.",
    expected: "Refresh plan.md with the full live cron set.",
    files: [{ path: ".lovable/plan.md" }],
    fixSize: "S",
  },
  {
    id: "billing-trial-days-magic-number",
    area: "Marketing",
    severity: "P3",
    status: "fixed",
    title: "Trial length 60 duplicated across edge functions",
    observed: "Shared constant module supabase/functions/_shared/trial.ts now exports TRIAL_DAYS, TRIAL_ONBOARDING_DAYS, TRIAL_LIVE_USE_DAYS and TRIAL_LABEL. Future edge-function refactors import from this single source.",
    expected: "Shared TRIAL_DAYS constant + shared copy string.",
    files: [{ path: "supabase/functions/_shared/trial.ts" }],
    memoryRef: "mem://product/trial-period-standard",
    fixSize: "S",
  },
  {
    id: "edge-check-subscription-silent-error",
    area: "Edge functions",
    severity: "P3",
    status: "fixed",
    title: "check-subscription returns 200/subscribed:false on internal errors",
    observed: "FIXED — error payload now includes `lookup_failed: true` alongside `subscribed: false` so callers can distinguish genuinely unsubscribed from a Stripe/auth outage while preserving the 200 OK contract per Sub Check Edge Handling standard.",
    expected: "Distinguish 'genuinely unsubscribed' vs 'lookup failed' in payload.",
    files: [{ path: "supabase/functions/check-subscription/index.ts", lines: "374-388" }],
    fixSize: "S",
  },
  {
    id: "customer-chat-widget-install-methods-verify",
    area: "Help / guides",
    severity: "P3",
    status: "open",
    title: "Only 2 of 3 documented chat widget install methods verified",
    observed: "iframe embed (booking.js) and Widget.tsx confirmed; no clear third install path surface.",
    expected: "Settings page linking to all 3 install methods per mem.",
    files: [{ path: "public/embed/booking.js" }, { path: "src/pages/Widget.tsx" }],
    memoryRef: "mem://features/web-presence/chat-widget-installation-standard",
    fixSize: "S",
  },
  {
    id: "field-ops-fab-no-safe-area",
    area: "CSS / theme",
    severity: "P3",
    status: "open",
    title: "Technician FAB uses hardcoded bottom-20 offset, no safe-area-inset",
    observed: "src/pages/technician/TechnicianDashboard.tsx:419.",
    expected: "env(safe-area-inset-bottom) support for notched devices.",
    files: [{ path: "src/pages/technician/TechnicianDashboard.tsx", lines: "419" }],
    memoryRef: "mem://features/field-ops/mobile-technician-ux-standard",
    fixSize: "S",
  },
  {
    id: "industry-empty-states-single-key",
    area: "Help / guides",
    severity: "P3",
    status: "open",
    title: "industryEmptyStates.ts branches per-industry for only 1 key",
    observed: "Structure suggests only 1 quoted industry key vs 21+ elsewhere.",
    expected: "Per-industry empty-state copy for all 28 packs.",
    files: [{ path: "src/lib/industryEmptyStates.ts" }],
    memoryRef: "mem://features/ux/industry-empty-states",
    fixSize: "S",
  },
  {
    id: "notifications-four-channel-fanout-unverified",
    area: "Settings & integrations",
    severity: "P3",
    status: "open",
    title: "4-channel staff notification fan-out not per-channel verified",
    observed: "send-staff-notification/index.ts exists (282 lines); per-channel dispatch not traced end-to-end.",
    expected: "Confirm push (SW), email (Resend), SMS (SignalWire), and in-app bell insert all fire from the same event.",
    files: [{ path: "supabase/functions/send-staff-notification/index.ts" }],
    memoryRef: "mem://features/notifications/staff-alert-system",
    fixSize: "S",
  },
  {
    id: "onboarding-10dlc-not-discrete-step",
    area: "Workflow handoffs",
    severity: "P3",
    status: "open",
    title: "10DLC not a discrete SignUp wizard step",
    observed: "SignUp.tsx only references/links to 10DLC; discrete blocking step lives elsewhere (Campaigns/SMSLogs/Subscription).",
    expected: "Confirm intent — if signup should collect A2P info, add as a step.",
    files: [{ path: "src/pages/SignUp.tsx" }],
    fixSize: "S",
  },
  {
    id: "pwa-sw-no-cache-scope-logic",
    area: "CSS / theme",
    severity: "P3",
    status: "open",
    title: "public/sw.js has zero fetch/cache/scope logic",
    observed: "Only push/notificationclick/install/activate; no fetch handler or scope enforcement.",
    expected: "Cache allow/deny list + scope restriction per (missing) PWA standard doc.",
    files: [{ path: "public/sw.js" }],
    fixSize: "M",
  },
  {
    id: "naming-central-control-center-residual",
    area: "Naming drift",
    severity: "P3",
    status: "fixed",
    title: "PricingComparisonTable still uses 'Central control center' wording",
    observed: "Replaced with 'Your hub for managing and monitoring all AI operatives.' in both src/components/landing/PricingComparisonTable.tsx and src/pages/Subscription.tsx.",
    expected: "Match canonical naming registry (consoles / hub).",
    files: [{ path: "src/components/landing/PricingComparisonTable.tsx", lines: "49" }, { path: "src/pages/Subscription.tsx", lines: "69" }],
    memoryRef: "mem://architecture/canonical-naming-registry",
    fixSize: "S",
  },
  {
    id: "test-orchestrator-proposals-untested",
    area: "Edge functions",
    severity: "P3",
    status: "open",
    title: "orchestrator-proposals has no test coverage",
    observed: "No test files reference orchestrator-proposals.",
    expected: "Integration test verifying insert+read cycle for agent_proposed_actions.",
    files: [{ path: "supabase/functions/orchestrator-proposals/index.ts" }],
    fixSize: "S",
  },
];
