import { type TutorialStep } from '@/hooks/useTutorial';

export const dashboardTutorialSteps: TutorialStep[] = [
  // Overview
  {
    id: 'welcome',
    title: 'Welcome to Aura Intercept',
    description: 'This tutorial walks you through every section of the platform. You\'ll learn how your AI agents, consoles, and integrations work together to automate your business.',
    tip: 'You can pause and resume this tutorial anytime — your progress is saved.',
    targetSelector: '[data-tour-id="sidebar-logo"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'dashboard-overview',
    title: 'Your Dashboard',
    description: 'This is your command center. It shows key metrics, upcoming appointments, and agent activity at a glance.',
    tip: 'The dashboard adapts based on your subscription tier and role.',
    targetSelector: '[data-tour-id="main-content"]',
    route: '/dashboard',
    position: 'bottom',
  },
  {
    id: 'quick-setup',
    title: 'Quick Setup',
    description: 'Configure your company profile, business hours, service types, and branding. This information powers your AI agents\' responses.',
    tryIt: 'Click Quick Setup in the sidebar to explore company settings.',
    targetSelector: '[data-tour-id="nav-quick-setup"]',
    route: '/dashboard',
    position: 'right',
  },
  // Customer Console
  {
    id: 'customer-portal',
    title: 'Customer Portal Console',
    description: 'Manage how customers interact with your business. This console handles appointment booking, AI chat, and customer communications.',
    tip: 'Your customers get a free mobile-friendly portal with real-time tracking.',
    targetSelector: '[data-tour-id="nav-customer-portal"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'customer-website-app',
    title: 'Customer Website App',
    description: 'Embed an AI chat widget on your website. Customers can book appointments, get quotes, and chat with your AI receptionist 24/7.',
    targetSelector: '[data-tour-id="nav-customer-website-app"]',
    route: '/dashboard',
    position: 'right',
  },
  // Business Management
  {
    id: 'business-mgt',
    title: 'Business Management Console',
    description: 'Your central hub for operations: appointments, leads, quotes, invoices, inventory, and employee management all in one place.',
    tryIt: 'Open the Business Mgt Ops Console to see the Aura Live activity feed.',
    targetSelector: '[data-tour-id="nav-business-mgt-ops"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'analytics-reports',
    title: 'Analytics & Reports',
    description: 'Deep-dive analytics powered by AI. Revenue trends, customer insights, performance metrics, and forecasting — all generated automatically.',
    tip: 'Available on Performance and Command tiers.',
    targetSelector: '[data-tour-id="nav-analytics-reports"]',
    route: '/dashboard',
    position: 'right',
  },
  // Marketing
  {
    id: 'marketing-sales',
    title: 'Outreach & Sales Ops',
    description: 'Run email campaigns, SMS blasts, and lead nurturing sequences. The marketing agent creates content, and the campaign agent handles delivery.',
    targetSelector: '[data-tour-id="nav-marketing-sales"]',
    route: '/dashboard',
    position: 'right',
  },
  // Social Media
  {
    id: 'social-media',
    title: 'Social Media Ops',
    description: 'Schedule posts, analyze engagement, and manage your social presence across platforms. AI generates content tailored to your brand voice.',
    targetSelector: '[data-tour-id="nav-social-media"]',
    route: '/dashboard',
    position: 'right',
  },
  // Web Presence
  {
    id: 'web-presence',
    title: 'Web Presence Manager',
    description: 'Build and manage your company website with AI-powered content generation, SEO optimization, and blog management.',
    targetSelector: '[data-tour-id="nav-web-presence"]',
    route: '/dashboard',
    position: 'right',
  },
  // Field Ops
  {
    id: 'field-ops',
    title: 'Technician-Field Ops',
    description: 'Manage field technicians with job assignments, route optimization, check-ins, and real-time tracking. Technicians get their own mobile app.',
    targetSelector: '[data-tour-id="nav-field-ops"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'dispatch-ops',
    title: 'Dispatch-Field Ops',
    description: 'Smart dispatching with AI-powered technician assignment based on location, skills, and workload. Includes live map tracking.',
    tip: 'The dispatch agent automatically assigns the best technician for each job.',
    targetSelector: '[data-tour-id="nav-dispatch-ops"]',
    route: '/dashboard',
    position: 'right',
  },
  // Configuration
  {
    id: 'ai-operatives-hub',
    title: 'AI Operatives Hub',
    description: 'The nerve center of your AI workforce. Enable/disable agents, monitor performance, view real-time events, and configure agent behavior.',
    tryIt: 'Open the Hub to see all 24 AI agents and their health status.',
    targetSelector: '[data-tour-id="nav-ai-operatives"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'knowledge-base',
    title: 'Knowledge Base',
    description: 'Train your AI agents with company-specific information. Upload FAQs, service details, pricing, and policies that agents reference during conversations.',
    tip: 'The more you add, the smarter your agents become.',
    targetSelector: '[data-tour-id="nav-knowledge-base"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'calculators',
    title: 'Cost Calculators',
    description: 'Estimate your monthly costs for SMS, email, voice, and other services based on your appointment volume.',
    targetSelector: '[data-tour-id="nav-calculators"]',
    route: '/dashboard',
    position: 'right',
  },
  // Integrations
  {
    id: 'integrations-overview',
    title: '3rd Party Integrations',
    description: 'Connect external services that power your AI agents: voice (ElevenLabs), SMS (SignalWire), email (Resend), calendar (Google), and more.',
    tryIt: 'Click 3rd Party Overview to see all available integrations and their setup status.',
    targetSelector: '[data-tour-id="nav-integrations-overview"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'voice-integration',
    title: 'Voice Agent (ElevenLabs)',
    description: 'Connect ElevenLabs for natural-sounding AI voice conversations. Your AI receptionist answers calls with a human-like voice 24/7.',
    targetSelector: '[data-tour-id="nav-voice-agent"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'sms-integration',
    title: 'Voice & SMS (SignalWire)',
    description: 'Set up phone numbers for inbound/outbound calling and SMS. Handles appointment reminders, confirmations, and two-way messaging.',
    targetSelector: '[data-tour-id="nav-voice-sms"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'email-integration',
    title: 'Email (Resend)',
    description: 'Configure email for appointment confirmations, reminders, marketing campaigns, and review requests.',
    targetSelector: '[data-tour-id="nav-email"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'calendar-integration',
    title: 'Calendar (Google)',
    description: 'Sync appointments bidirectionally with Google Calendar. New bookings appear on your calendar, and calendar events sync back.',
    tip: 'Use the same email for signup and Google Calendar for automatic connection.',
    targetSelector: '[data-tour-id="nav-calendar"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'social-integration',
    title: 'Social Media Integration',
    description: 'Connect your Facebook and Instagram pages for automated content publishing and engagement tracking.',
    targetSelector: '[data-tour-id="nav-social-integration"]',
    route: '/dashboard',
    position: 'right',
  },
  {
    id: 'tavily-integration',
    title: 'AI Research (Tavily)',
    description: 'Enhance AI content quality with real-time web research. Agents use Tavily to find current information for blog posts, social content, and customer answers.',
    targetSelector: '[data-tour-id="nav-ai-research"]',
    route: '/dashboard',
    position: 'right',
  },
  // Subscription
  {
    id: 'subscription',
    title: 'Subscription & Billing',
    description: 'Manage your plan, view usage, and upgrade or downgrade your subscription tier. Your 30-day trial includes all Command-tier features.',
    targetSelector: '[data-tour-id="nav-subscription"]',
    route: '/dashboard',
    position: 'right',
  },
  // Help
  {
    id: 'help',
    title: 'Help & Support',
    description: 'Access documentation, platform guides, and the AI help center. Report issues directly from the sidebar.',
    targetSelector: '[data-tour-id="nav-help"]',
    route: '/dashboard',
    position: 'right',
  },
  // Completion
  {
    id: 'tutorial-complete',
    title: 'Tutorial Complete! 🎉',
    description: 'You\'ve explored all sections of Aura Intercept. Your AI agents are ready to start automating your business. Start by configuring Quick Setup, then connect your integrations.',
    tip: 'Need help? Use the floating Aura button in the bottom-right corner to chat with your AI assistant anytime.',
    targetSelector: '[data-tour-id="sidebar-logo"]',
    route: '/dashboard',
    position: 'right',
  },
];
