
-- Seed quote_template and invoice_template for all 28 industry packs
-- Shape: { line_items: [{description, quantity, unit_price, taxable}], default_tax_rate, default_terms, footer_note }

WITH seeds(industry_id, q_items, i_items, terms) AS (
  VALUES
    -- BOOKING / HEALTHCARE
    ('dental',
     '[{"description":"Comprehensive Oral Exam","quantity":1,"unit_price":150,"taxable":false},
       {"description":"Adult Prophylaxis (Cleaning)","quantity":1,"unit_price":120,"taxable":false},
       {"description":"Bitewing X-Rays (4 films)","quantity":1,"unit_price":75,"taxable":false},
       {"description":"Fluoride Treatment","quantity":1,"unit_price":40,"taxable":false}]'::jsonb,
     '[{"description":"Office Visit Copay","quantity":1,"unit_price":50,"taxable":false}]'::jsonb,
     'Treatment plan estimate. Insurance coverage may vary.'),
    ('veterinary',
     '[{"description":"Wellness Exam","quantity":1,"unit_price":75,"taxable":false},
       {"description":"DHPP Vaccination","quantity":1,"unit_price":35,"taxable":false},
       {"description":"Rabies Vaccination","quantity":1,"unit_price":30,"taxable":false},
       {"description":"Heartworm Test","quantity":1,"unit_price":50,"taxable":false}]'::jsonb,
     '[{"description":"Office Visit","quantity":1,"unit_price":75,"taxable":false}]'::jsonb,
     'Estimate only. Final charges depend on patient findings.'),
    ('chiropractic',
     '[{"description":"Initial Consultation & Exam","quantity":1,"unit_price":125,"taxable":false},
       {"description":"Spinal Adjustment","quantity":1,"unit_price":65,"taxable":false},
       {"description":"Therapeutic Modalities","quantity":1,"unit_price":45,"taxable":false}]'::jsonb,
     '[{"description":"Adjustment Visit","quantity":1,"unit_price":65,"taxable":false}]'::jsonb,
     'Care plan estimate. HSA/FSA accepted.'),
    ('medical_office',
     '[{"description":"New Patient Visit","quantity":1,"unit_price":175,"taxable":false},
       {"description":"Lab Work (Basic Panel)","quantity":1,"unit_price":85,"taxable":false}]'::jsonb,
     '[{"description":"Office Visit Copay","quantity":1,"unit_price":40,"taxable":false}]'::jsonb,
     'Estimate. Insurance may cover a portion.'),
    ('physical_therapy',
     '[{"description":"Initial Evaluation","quantity":1,"unit_price":150,"taxable":false},
       {"description":"Therapeutic Exercise (per unit)","quantity":4,"unit_price":35,"taxable":false},
       {"description":"Manual Therapy (per unit)","quantity":2,"unit_price":40,"taxable":false}]'::jsonb,
     '[{"description":"Therapy Session","quantity":1,"unit_price":120,"taxable":false}]'::jsonb,
     'Plan of care estimate.'),
    ('optometry',
     '[{"description":"Comprehensive Eye Exam","quantity":1,"unit_price":135,"taxable":false},
       {"description":"Contact Lens Fitting","quantity":1,"unit_price":75,"taxable":false}]'::jsonb,
     '[{"description":"Eye Exam","quantity":1,"unit_price":135,"taxable":false}]'::jsonb,
     'Estimate. Vision insurance may apply.'),
    ('salon',
     '[{"description":"Haircut & Style","quantity":1,"unit_price":65,"taxable":true},
       {"description":"Color Service","quantity":1,"unit_price":120,"taxable":true},
       {"description":"Conditioning Treatment","quantity":1,"unit_price":35,"taxable":true}]'::jsonb,
     '[{"description":"Service","quantity":1,"unit_price":65,"taxable":true},
       {"description":"Retail Product","quantity":0,"unit_price":0,"taxable":true}]'::jsonb,
     'Gratuity not included.'),
    ('beauty_wellness',
     '[{"description":"Signature Treatment","quantity":1,"unit_price":120,"taxable":true},
       {"description":"Add-On Service","quantity":1,"unit_price":40,"taxable":true}]'::jsonb,
     '[{"description":"Service","quantity":1,"unit_price":120,"taxable":true}]'::jsonb,
     'Receipt. Gratuity appreciated.'),
    ('fitness',
     '[{"description":"Fitness Assessment","quantity":1,"unit_price":75,"taxable":false},
       {"description":"Personal Training Session (60 min)","quantity":10,"unit_price":85,"taxable":false}]'::jsonb,
     '[{"description":"Membership / Session Pack","quantity":1,"unit_price":250,"taxable":false}]'::jsonb,
     'Sessions expire 90 days from purchase.'),
    ('professional',
     '[{"description":"Discovery Consultation","quantity":1,"unit_price":250,"taxable":false},
       {"description":"Professional Services (per hour)","quantity":10,"unit_price":175,"taxable":false}]'::jsonb,
     '[{"description":"Professional Services","quantity":1,"unit_price":1750,"taxable":false}]'::jsonb,
     'Net 15. Retainers due in advance.'),
    ('personal_assistant',
     '[{"description":"Concierge Hours","quantity":10,"unit_price":75,"taxable":false}]'::jsonb,
     '[{"description":"Concierge Services","quantity":1,"unit_price":750,"taxable":false}]'::jsonb,
     'Net 15.'),
    ('real_estate',
     '[{"description":"Listing Commission (% of sale)","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Marketing Package","quantity":1,"unit_price":500,"taxable":false}]'::jsonb,
     '[{"description":"Commission Earned","quantity":1,"unit_price":0,"taxable":false}]'::jsonb,
     'Commission per listing agreement.'),
    ('restaurants',
     '[{"description":"Catering Deposit","quantity":1,"unit_price":250,"taxable":false},
       {"description":"Per-Guest Catering","quantity":25,"unit_price":35,"taxable":true}]'::jsonb,
     '[{"description":"Catering Total","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     'Final headcount due 72 hours prior.'),
    ('saas_platform',
     '[{"description":"Implementation","quantity":1,"unit_price":2500,"taxable":false},
       {"description":"Annual Subscription","quantity":1,"unit_price":12000,"taxable":false}]'::jsonb,
     '[{"description":"Subscription Period","quantity":1,"unit_price":1000,"taxable":false}]'::jsonb,
     'Net 30.'),
    -- TRADES / OUTDOOR / REPAIR
    ('hvac',
     '[{"description":"Diagnostic Service Call","quantity":1,"unit_price":99,"taxable":false},
       {"description":"Labor (per hour)","quantity":2,"unit_price":125,"taxable":false},
       {"description":"Parts & Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Service Call","quantity":1,"unit_price":99,"taxable":false},
       {"description":"Labor","quantity":1,"unit_price":125,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     'Estimate valid for 30 days. Net 15 on completion.'),
    ('plumbing',
     '[{"description":"Service Call / Diagnostic","quantity":1,"unit_price":89,"taxable":false},
       {"description":"Labor (per hour)","quantity":2,"unit_price":135,"taxable":false},
       {"description":"Parts & Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Service Call","quantity":1,"unit_price":89,"taxable":false},
       {"description":"Labor","quantity":1,"unit_price":135,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     'Estimate valid for 30 days.'),
    ('electrical',
     '[{"description":"Service Call","quantity":1,"unit_price":95,"taxable":false},
       {"description":"Labor (per hour)","quantity":2,"unit_price":135,"taxable":false},
       {"description":"Parts & Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Service Call","quantity":1,"unit_price":95,"taxable":false},
       {"description":"Labor","quantity":1,"unit_price":135,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     'Permits billed at cost.'),
    ('appliance_repair',
     '[{"description":"Diagnostic","quantity":1,"unit_price":89,"taxable":false},
       {"description":"Labor","quantity":1,"unit_price":120,"taxable":false},
       {"description":"Parts","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Service","quantity":1,"unit_price":89,"taxable":false},
       {"description":"Parts","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '90-day labor warranty.'),
    ('roofing',
     '[{"description":"Roof Inspection","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Materials (per square)","quantity":20,"unit_price":275,"taxable":true},
       {"description":"Labor (per square)","quantity":20,"unit_price":225,"taxable":false},
       {"description":"Disposal & Cleanup","quantity":1,"unit_price":450,"taxable":false}]'::jsonb,
     '[{"description":"Roofing Project","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '50% deposit. Balance due on completion.'),
    ('landscape',
     '[{"description":"Site Assessment","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Labor (per hour)","quantity":8,"unit_price":75,"taxable":false},
       {"description":"Materials & Plants","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Service Visit","quantity":1,"unit_price":150,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     'Recurring service billed monthly.'),
    ('pest_control',
     '[{"description":"Initial Treatment","quantity":1,"unit_price":175,"taxable":false},
       {"description":"Quarterly Service Plan","quantity":4,"unit_price":95,"taxable":false}]'::jsonb,
     '[{"description":"Service Visit","quantity":1,"unit_price":95,"taxable":false}]'::jsonb,
     'Service guarantee between visits.'),
    ('pool_spa',
     '[{"description":"Initial Inspection","quantity":1,"unit_price":85,"taxable":false},
       {"description":"Weekly Service","quantity":4,"unit_price":120,"taxable":false},
       {"description":"Chemicals","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Monthly Service","quantity":1,"unit_price":480,"taxable":false},
       {"description":"Chemicals","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     'Equipment repairs billed separately.'),
    ('fencing',
     '[{"description":"Site Measurement","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Materials (per linear ft)","quantity":100,"unit_price":18,"taxable":true},
       {"description":"Labor (per linear ft)","quantity":100,"unit_price":12,"taxable":false}]'::jsonb,
     '[{"description":"Fencing Project","quantity":1,"unit_price":0,"taxable":false}]'::jsonb,
     '50% deposit. Balance on completion.'),
    ('solar',
     '[{"description":"Site Assessment & Design","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Solar Panels (per kW)","quantity":8,"unit_price":1200,"taxable":true},
       {"description":"Inverter & BOS","quantity":1,"unit_price":2500,"taxable":true},
       {"description":"Installation Labor","quantity":1,"unit_price":3500,"taxable":false}]'::jsonb,
     '[{"description":"Solar Installation","quantity":1,"unit_price":0,"taxable":false}]'::jsonb,
     'Federal tax credit may apply. Permits at cost.'),
    ('auto_care',
     '[{"description":"Diagnostic","quantity":1,"unit_price":120,"taxable":false},
       {"description":"Labor (per hour)","quantity":2,"unit_price":140,"taxable":false},
       {"description":"Parts","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Labor","quantity":1,"unit_price":140,"taxable":false},
       {"description":"Parts","quantity":1,"unit_price":0,"taxable":true},
       {"description":"Shop Supplies","quantity":1,"unit_price":15,"taxable":true}]'::jsonb,
     '12-month/12k-mile warranty on parts and labor.'),
    ('construction',
     '[{"description":"Site Survey & Design","quantity":1,"unit_price":1500,"taxable":false},
       {"description":"Labor (per day)","quantity":10,"unit_price":1200,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true},
       {"description":"Permits","quantity":1,"unit_price":0,"taxable":false}]'::jsonb,
     '[{"description":"Draw Request","quantity":1,"unit_price":0,"taxable":false}]'::jsonb,
     'Progress billing per draw schedule.'),
    ('handyman',
     '[{"description":"Service Call","quantity":1,"unit_price":75,"taxable":false},
       {"description":"Labor (per hour)","quantity":2,"unit_price":85,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '[{"description":"Labor","quantity":1,"unit_price":85,"taxable":false},
       {"description":"Materials","quantity":1,"unit_price":0,"taxable":true}]'::jsonb,
     '1-hour minimum.'),
    ('security_systems',
     '[{"description":"Site Walk-Through","quantity":1,"unit_price":0,"taxable":false},
       {"description":"Equipment","quantity":1,"unit_price":1200,"taxable":true},
       {"description":"Installation Labor","quantity":1,"unit_price":650,"taxable":false},
       {"description":"Monitoring (monthly)","quantity":12,"unit_price":45,"taxable":false}]'::jsonb,
     '[{"description":"Monitoring","quantity":1,"unit_price":45,"taxable":false},
       {"description":"Service Visit","quantity":1,"unit_price":0,"taxable":false}]'::jsonb,
     '36-month monitoring agreement.')
)
UPDATE public.industry_template_packs p
SET quote_template = jsonb_build_object(
      'line_items', s.q_items,
      'default_tax_rate', 0,
      'default_terms', s.terms,
      'footer_note', 'Thank you for your business.'
    ),
    invoice_template = jsonb_build_object(
      'line_items', s.i_items,
      'default_tax_rate', 0,
      'default_terms', s.terms,
      'footer_note', 'Payment due as noted above. Thank you.'
    ),
    updated_at = now()
FROM seeds s
WHERE p.industry_id = s.industry_id;
